export const GET_PLAYERS_START = "GET_PLAYERS_START";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_ERROR = "GET_PLAYERS_ERROR";

export const SAVE_PLAYERS_START = "SAVE_PLAYERS_START";
export const SAVE_PLAYERS_SUCCESS = "SAVE_PLAYERS_SUCCESS";
export const SAVE_PLAYERS_ERROR = "SAVE_PLAYERS_ERROR";

export const DELETE_PLAYERS_START = "DELETE_PLAYERS_START";
export const DELETE_PLAYERS_SUCCESS = "DELETE_PLAYERS_SUCCESS";
export const DELETE_PLAYERS_ERROR = "DELETE_PLAYERS_ERROR";